version: '3'
services:
  app:
    image: ubuntu:18.04
    ports:
      - 9000:9000
    volumes:
      - ./dockerapp:/files/dockerapp
      - ./wait-for-it.sh:/files/wait-for-it.sh
    command: sh -c './files/wait-for-it.sh postgres:5432 -- /files/dockerapp'
    depends_on:
      - postgres
  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=route-db