version: '3'
services:
  app:
    image: ubuntu
    ports:
      - 9000:9000

  postgres:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./init/postgres:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_DB=route-db